// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tesjdmhohedlannpgvct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlc2pkbWhvaGVkbGFubnBndmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMTIxMDUsImV4cCI6MjA1MzU4ODEwNX0.3eAkXH6jrm1wFJVUK87k8XAYiwsApzHt9u5MotrA4pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);