// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knoebbqglkhhxkunuvoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub2ViYnFnbGtoaHhrdW51dm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NzcxMTQsImV4cCI6MjA1MzM1MzExNH0.vsSJsrRK-Elyb1MMvRJZKSYfwBbOlSkQafCeEJbsCcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);